### ISSUE TITLE
Empty g_scale after safe_hw_from_asc

### ISSUE THREAD

**Issue by mrikasper** [filip-szczepankiewicz/safe_pns_prediction#1]
Dear Filip and Thomas,

Thank you for creating such an excellent tool and documentation. We got it to run swiftly with our simulated spiral gradients. However, when we run

`hw = safe_hw_from_asc('MP_GPA_K2309_2250V_951A_AS82_GSWD_SAFETY.asc')`

the parameters `hw.x/y/z.g_scale` remain empty and `safe_gwf_to_pns` subsequently fails. It seems that the relevant parameter `GScaleFactorX` is not specified in our`.asc` files (Numaris XA30 on a Siemens 3T Prisma).

Do you have any pointers to what this parameter means and where we could look for it? At the moment, the PNS simulation in the IDEA simulator trips whereas your simulation code does not, and we presume this could be the reason.

Thank you for your help and 

All the best,
Lars

![gradients502](https://user-images.githubusercontent.com/13321311/155635873-53b4bd9f-5c4a-43c2-ac63-47f5243cada3.png)

**Comment by filip-szczepankiewicz** [comment]
Dear Lars,

I think that the file you are reading is a special addon to the general system specs found in MP_GPA_K2309_2250V_951A_AS82.asc.

As you see at the bottom of that file, it also has a dependency on the file that you are using (with GSWD_SAFETY at the end). It i my guess that you get the correct hw spec if you read in the base file and let it such in the extra info from the dependency. 

However, it appears (from testing on XA31A) that the format is somewhat different and I need to create a smarter merge function when dependencies exist. I made and update that works for me using XA31A.

Please pull the repo again, and see if building the hw structure based on the basic file (MP_GPA_K2309_2250V_951A_AS82.asc) works now.

Best,
/F

**Comment by mrikasper** [comment]
Dear Filip,

Thank you for looking into this. 

1. I can confirm that with the previous version of the code,  `hw = safe_hw_from_asc('MP_GPA_K2309_2250V_951A_AS82.asc')` (without the GSWD_SAFETY at the end) also returned empty `g_scale` fields.
2. After your code update, it now runs through smoothly and finds the `g_scale` for all axes. That's great!
3. The initial PNS threshold mismatch between the Siemens simulator (POET) and your code I reported, was an error on our side. We forgot to simulate the gradients before the readout (especially the diffusion encoding) on the Matlab side. Sorry for the confusion.

Thank you so much again for resolving this issue so quickly!

All the best,
Lars
